#!/bin/bash
#
# AIDN - Fail2ban Setup Script
# Configures fail2ban for SSH and game server protection on Debian
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Paths
F2B_JAIL_LOCAL="/etc/fail2ban/jail.local"
F2B_FILTER_DIR="/etc/fail2ban/filter.d"
F2B_JAIL_BACKUP=""

# Logging functions (defined early for use in cleanup)
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Cleanup handler for unexpected exits
cleanup() {
    local exit_code=$?
    if [[ $exit_code -ne 0 ]]; then
        log_error "Script failed with exit code $exit_code"
        if [[ -n "$F2B_JAIL_BACKUP" ]] && [[ -f "$F2B_JAIL_BACKUP" ]]; then
            log_warn "Restoring fail2ban configuration from backup..."
            cp "$F2B_JAIL_BACKUP" "$F2B_JAIL_LOCAL" 2>/dev/null || true
            systemctl restart fail2ban 2>/dev/null || true
        fi
    fi
}
trap cleanup EXIT

# Input validation functions
validate_ip() {
    local ip="$1"
    # Match IPv4 address with optional CIDR notation
    if [[ ! "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}(/[0-9]{1,2})?$ ]]; then
        log_error "Invalid IP address: $ip"
        return 1
    fi
    # Validate each octet is 0-255
    local IFS='.'
    read -ra octets <<< "${ip%%/*}"
    for octet in "${octets[@]}"; do
        if [[ "$octet" -gt 255 ]]; then
            log_error "Invalid IP address: $ip (octet $octet > 255)"
            return 1
        fi
    done
    return 0
}

validate_port() {
    local port="$1"
    if [[ ! "$port" =~ ^[0-9]+$ ]] || [[ "$port" -lt 1 ]] || [[ "$port" -gt 65535 ]]; then
        log_error "Invalid port number: $port (must be 1-65535)"
        return 1
    fi
    return 0
}

validate_jail() {
    local jail="$1"
    if ! fail2ban-client status "$jail" >/dev/null 2>&1; then
        log_error "Jail '$jail' does not exist or fail2ban is not running"
        return 1
    fi
    return 0
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

check_fail2ban_installed() {
    if ! command -v fail2ban-client &> /dev/null; then
        log_error "fail2ban is not installed. Run '$0 setup' first."
        exit 1
    fi
}

install_fail2ban() {
    log_info "Installing fail2ban..."
    apt-get update -qq
    apt-get install -y -qq fail2ban
    log_info "Fail2ban installed"
}

configure_jail_local() {
    local ssh_port="${1:-10022}"
    local ban_time="${2:-3600}"
    local find_time="${3:-600}"
    local max_retry="${4:-3}"

    log_info "Configuring fail2ban jails..."

    cat > "$F2B_JAIL_LOCAL" << EOF
# AIDN Fail2ban Configuration
# Generated by AIDN fail2ban-setup.sh

[DEFAULT]
# Ban settings
bantime = ${ban_time}
findtime = ${find_time}
maxretry = ${max_retry}

# Action settings
banaction = iptables-multiport
banaction_allports = iptables-allports

# Ignore localhost
ignoreip = 127.0.0.1/8 ::1

# Backend
backend = systemd

#
# SSH Jail
#
[sshd]
enabled = true
port = ${ssh_port}
filter = sshd
logpath = /var/log/auth.log
maxretry = 3
bantime = 3600
findtime = 600

#
# SSH DDoS Protection (aggressive)
#
[sshd-ddos]
enabled = true
port = ${ssh_port}
filter = sshd-ddos
logpath = /var/log/auth.log
maxretry = 5
bantime = 86400
findtime = 300

#
# Recidive - ban repeat offenders for longer
#
[recidive]
enabled = true
filter = recidive
logpath = /var/log/fail2ban.log
bantime = 604800
findtime = 86400
maxretry = 3
EOF

    log_info "Jail configuration written to $F2B_JAIL_LOCAL"
}

create_sshd_ddos_filter() {
    log_info "Creating SSH DDoS filter..."

    cat > "$F2B_FILTER_DIR/sshd-ddos.conf" << 'EOF'
# AIDN - SSH DDoS Filter
# Detects connection flooding

[Definition]
failregex = ^.*sshd.*: Connection from <HOST>.*$
            ^.*sshd.*: Received disconnect from <HOST>.*\[preauth\]$
            ^.*sshd.*: Disconnected from <HOST>.*\[preauth\]$

ignoreregex =
EOF

    log_info "SSH DDoS filter created"
}

create_game_server_jail() {
    local jail_name="$1"
    local ports="$2"
    local log_path="$3"
    local filter_name="$4"

    log_info "Adding game server jail: $jail_name"

    cat >> "$F2B_JAIL_LOCAL" << EOF

#
# Game Server: $jail_name
#
[$jail_name]
enabled = true
port = $ports
protocol = udp
filter = $filter_name
logpath = $log_path
maxretry = 10
bantime = 1800
findtime = 60
banaction = iptables-multiport[protocol=udp]
EOF

    log_info "Game server jail '$jail_name' added"
}

create_arma_reforger_filter() {
    log_info "Creating Arma Reforger filter..."

    cat > "$F2B_FILTER_DIR/arma-reforger.conf" << 'EOF'
# AIDN - Arma Reforger Game Server Filter
# Detects connection flooding and invalid packets

[Definition]
# Match rapid connection attempts
failregex = ^.*Connection from <HOST>.*rejected.*$
            ^.*Invalid packet from <HOST>.*$
            ^.*<HOST>.*connection refused.*$

ignoreregex =
EOF

    log_info "Arma Reforger filter created"
}

setup_arma_reforger() {
    local log_path="${1:-/var/log/arma-reforger.log}"
    local ports="${2:-2001,2002,17777,19999}"

    create_arma_reforger_filter
    create_game_server_jail "arma-reforger" "$ports" "$log_path" "arma-reforger"
}

restart_fail2ban() {
    log_info "Restarting fail2ban..."
    systemctl restart fail2ban

    # Wait for fail2ban to start with timeout (max 30 seconds)
    local max_attempts=15
    local attempt=0

    while [[ $attempt -lt $max_attempts ]]; do
        sleep 2
        if systemctl is-active --quiet fail2ban; then
            log_info "Fail2ban restarted successfully"
            return 0
        fi
        attempt=$((attempt + 1))
        log_info "Waiting for fail2ban to start... (attempt $attempt/$max_attempts)"
    done

    log_error "Fail2ban failed to start within 30 seconds!"
    journalctl -u fail2ban -n 20
    exit 1
}

show_status() {
    echo ""
    echo "=================================================="
    echo "Fail2ban Status"
    echo "=================================================="
    fail2ban-client status

    echo ""
    echo "Jail Details:"
    echo ""

    for jail in $(fail2ban-client status | grep "Jail list:" | sed 's/.*://;s/,//g'); do
        echo "--- $jail ---"
        fail2ban-client status "$jail" 2>/dev/null || true
        echo ""
    done
}

unban_ip() {
    local ip="$1"
    local jail="${2:-}"

    if [[ -z "$ip" ]]; then
        log_error "IP address required"
        return 1
    fi

    if ! validate_ip "$ip"; then
        return 1
    fi

    if [[ -z "$jail" ]]; then
        log_info "Unbanning $ip from all jails..."
        if fail2ban-client unban "$ip" 2>/dev/null; then
            log_info "Successfully unbanned $ip"
        else
            log_warn "IP $ip was not banned or already unbanned"
        fi
    else
        if ! validate_jail "$jail"; then
            return 1
        fi
        log_info "Unbanning $ip from $jail..."
        if fail2ban-client set "$jail" unbanip "$ip" 2>/dev/null; then
            log_info "Successfully unbanned $ip from $jail"
        else
            log_warn "IP $ip was not banned in $jail or already unbanned"
        fi
    fi
}

ban_ip() {
    local ip="$1"
    local jail="${2:-sshd}"

    if [[ -z "$ip" ]]; then
        log_error "IP address required"
        return 1
    fi

    if ! validate_ip "$ip"; then
        return 1
    fi

    if ! validate_jail "$jail"; then
        return 1
    fi

    log_info "Banning $ip in jail $jail..."
    if fail2ban-client set "$jail" banip "$ip"; then
        log_info "Successfully banned $ip in $jail"
    else
        log_error "Failed to ban $ip in $jail"
        return 1
    fi
}

interactive_setup() {
    echo "=============================================="
    echo "AIDN - Fail2ban Setup"
    echo "=============================================="
    echo ""

    # SSH Port with validation
    local ssh_port
    while true; do
        read -p "SSH Port [10022]: " ssh_port
        ssh_port="${ssh_port:-10022}"
        if validate_port "$ssh_port" 2>/dev/null; then
            break
        fi
        echo "Please enter a valid port number (1-65535)"
    done

    # Ban time with validation
    local ban_time
    while true; do
        read -p "Ban time in seconds [3600]: " ban_time
        ban_time="${ban_time:-3600}"
        if [[ "$ban_time" =~ ^[0-9]+$ ]] && [[ "$ban_time" -gt 0 ]]; then
            break
        fi
        echo "Please enter a valid positive number"
    done

    # Max retry with validation
    local max_retry
    while true; do
        read -p "Max retry attempts [3]: " max_retry
        max_retry="${max_retry:-3}"
        if [[ "$max_retry" =~ ^[0-9]+$ ]] && [[ "$max_retry" -gt 0 ]]; then
            break
        fi
        echo "Please enter a valid positive number"
    done

    echo ""
    read -p "Setup Arma Reforger protection? [y/N]: " -n 1 -r
    echo
    local setup_arma="${REPLY}"

    echo ""
    echo "Configuration:"
    echo "  SSH Port: $ssh_port"
    echo "  Ban Time: $ban_time seconds"
    echo "  Max Retry: $max_retry"
    echo ""

    read -p "Proceed with setup? [y/N]: " -n 1 -r
    echo

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_warn "Aborted"
        exit 0
    fi

    install_fail2ban

    # Backup existing configuration if present
    if [[ -f "$F2B_JAIL_LOCAL" ]]; then
        F2B_JAIL_BACKUP="/etc/fail2ban/jail.local.backup.$(date +%Y%m%d%H%M%S)"
        log_info "Backing up existing configuration to $F2B_JAIL_BACKUP"
        cp "$F2B_JAIL_LOCAL" "$F2B_JAIL_BACKUP"
    fi

    configure_jail_local "$ssh_port" "$ban_time" "600" "$max_retry"
    create_sshd_ddos_filter

    if [[ $setup_arma =~ ^[Yy]$ ]]; then
        read -p "Arma Reforger log path [/var/log/arma-reforger.log]: " arma_log
        arma_log="${arma_log:-/var/log/arma-reforger.log}"
        setup_arma_reforger "$arma_log"
    fi

    restart_fail2ban
    show_status

    echo ""
    echo -e "${GREEN}Fail2ban configured successfully!${NC}"
    echo ""
}

print_usage() {
    echo "Usage: $0 [COMMAND] [OPTIONS]"
    echo ""
    echo "Commands:"
    echo "  setup          Interactive fail2ban setup"
    echo "  status         Show fail2ban status"
    echo "  ban IP [JAIL]  Ban an IP address"
    echo "  unban IP       Unban an IP address"
    echo "  restart        Restart fail2ban"
    echo ""
    echo "Examples:"
    echo "  $0 setup"
    echo "  $0 status"
    echo "  $0 ban 1.2.3.4 sshd"
    echo "  $0 unban 1.2.3.4"
    echo ""
}

main() {
    check_root

    case "${1:-}" in
        setup)
            interactive_setup
            ;;
        status)
            check_fail2ban_installed
            show_status
            ;;
        ban)
            check_fail2ban_installed
            if ! ban_ip "$2" "${3:-sshd}"; then
                exit 1
            fi
            ;;
        unban)
            check_fail2ban_installed
            if ! unban_ip "$2" "$3"; then
                exit 1
            fi
            ;;
        restart)
            check_fail2ban_installed
            restart_fail2ban
            ;;
        *)
            print_usage
            ;;
    esac
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
