#!/bin/bash
#
# AIDN - Fail2ban Setup Script
# Configures fail2ban for SSH and game server protection on Debian
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Paths
F2B_JAIL_LOCAL="/etc/fail2ban/jail.local"
F2B_FILTER_DIR="/etc/fail2ban/filter.d"

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

validate_ip() {
    local ip="$1"

    if [[ -z "$ip" ]]; then
        return 1
    fi

    # IPv4 validation
    if [[ "$ip" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
        local IFS='.'
        read -ra octets <<< "$ip"
        for octet in "${octets[@]}"; do
            if (( octet > 255 )); then
                return 1
            fi
        done
        return 0
    fi

    # IPv6 validation (simplified - accepts common formats)
    if [[ "$ip" =~ ^([0-9a-fA-F]{0,4}:){2,7}[0-9a-fA-F]{0,4}$ ]] || \
       [[ "$ip" =~ ^::([0-9a-fA-F]{1,4}:){0,5}[0-9a-fA-F]{1,4}$ ]] || \
       [[ "$ip" =~ ^[0-9a-fA-F]{1,4}::$ ]]; then
        return 0
    fi

    return 1
}

install_fail2ban() {
    log_info "Installing fail2ban..."
    apt-get update -qq
    apt-get install -y -qq fail2ban
    log_info "Fail2ban installed"
}

configure_jail_local() {
    local ssh_port="${1:-10022}"
    local ban_time="${2:-3600}"
    local find_time="${3:-600}"
    local max_retry="${4:-3}"

    log_info "Configuring fail2ban jails..."

    cat > "$F2B_JAIL_LOCAL" << EOF
# AIDN Fail2ban Configuration
# Generated by AIDN fail2ban-setup.sh

[DEFAULT]
# Ban settings
bantime = ${ban_time}
findtime = ${find_time}
maxretry = ${max_retry}

# Action settings
banaction = iptables-multiport
banaction_allports = iptables-allports

# Ignore localhost
ignoreip = 127.0.0.1/8 ::1

# Backend - auto detects systemd journal or log files
backend = auto

#
# SSH Jail
#
[sshd]
enabled = true
port = ${ssh_port}
filter = sshd
maxretry = 3
bantime = 3600
findtime = 600

#
# SSH DDoS Protection (aggressive)
#
[sshd-ddos]
enabled = true
port = ${ssh_port}
filter = sshd-ddos
maxretry = 5
bantime = 86400
findtime = 300

#
# Recidive - ban repeat offenders for longer
#
[recidive]
enabled = true
filter = recidive
logpath = /var/log/fail2ban.log
bantime = 604800
findtime = 86400
maxretry = 3
EOF

    log_info "Jail configuration written to $F2B_JAIL_LOCAL"
}

create_sshd_ddos_filter() {
    log_info "Creating SSH DDoS filter..."

    cat > "$F2B_FILTER_DIR/sshd-ddos.conf" << 'EOF'
# AIDN - SSH DDoS Filter
# Detects authentication abuse and connection flooding

[Definition]
# Match real abuse signals - authentication failures and invalid users
failregex = ^.*sshd\[\d+\]: Failed password for .* from <HOST>.*$
            ^.*sshd\[\d+\]: Failed password for invalid user .* from <HOST>.*$
            ^.*sshd\[\d+\]: Invalid user .* from <HOST>.*$
            ^.*sshd\[\d+\]: User .* from <HOST> not allowed because.*$
            ^.*sshd\[\d+\]: error: PAM: Authentication failure for .* from <HOST>.*$
            ^.*sshd\[\d+\]: Received disconnect from <HOST>.*: .* \[preauth\]$
            ^.*sshd\[\d+\]: Disconnected from authenticating user .* <HOST>.*\[preauth\]$
            ^.*sshd\[\d+\]: Connection reset by <HOST>.*\[preauth\]$
            ^.*sshd\[\d+\]: Unable to negotiate with <HOST>.*$
            ^.*sshd\[\d+\]: Bad protocol version identification.*from <HOST>.*$

# Ignore legitimate successful connections
ignoreregex = ^.*sshd\[\d+\]: Accepted (password|publickey) for .* from <HOST>.*$
              ^.*sshd\[\d+\]: Connection closed by authenticating user .* <HOST>.*$
              ^.*sshd\[\d+\]: pam_unix\(sshd:session\): session opened for user.*$
EOF

    log_info "SSH DDoS filter created"
}

create_game_server_jail() {
    local jail_name="$1"
    local ports="$2"
    local log_path="$3"
    local filter_name="$4"

    log_info "Adding game server jail: $jail_name"

    cat >> "$F2B_JAIL_LOCAL" << EOF

#
# Game Server: $jail_name
#
[$jail_name]
enabled = true
port = $ports
protocol = udp
filter = $filter_name
logpath = $log_path
maxretry = 10
bantime = 1800
findtime = 60
banaction = iptables-multiport[protocol=udp]
EOF

    log_info "Game server jail '$jail_name' added"
}

create_arma_reforger_filter() {
    log_info "Creating Arma Reforger filter..."

    cat > "$F2B_FILTER_DIR/arma-reforger.conf" << 'EOF'
# AIDN - Arma Reforger Game Server Filter
# Detects connection flooding and invalid packets

[Definition]
# Match rapid connection attempts
failregex = ^.*Connection from <HOST>.*rejected.*$
            ^.*Invalid packet from <HOST>.*$
            ^.*<HOST>.*connection refused.*$

ignoreregex =
EOF

    log_info "Arma Reforger filter created"
}

setup_arma_reforger() {
    local log_path="${1:-/var/log/arma-reforger.log}"
    local ports="${2:-2001,2002,17777,19999}"

    create_arma_reforger_filter
    create_game_server_jail "arma-reforger" "$ports" "$log_path" "arma-reforger"
}

restart_fail2ban() {
    log_info "Restarting fail2ban..."
    systemctl restart fail2ban

    sleep 2

    if systemctl is-active --quiet fail2ban; then
        log_info "Fail2ban restarted successfully"
    else
        log_error "Fail2ban failed to start!"
        journalctl -u fail2ban -n 20
        exit 1
    fi
}

show_status() {
    echo ""
    echo "=================================================="
    echo "Fail2ban Status"
    echo "=================================================="
    fail2ban-client status

    echo ""
    echo "Jail Details:"
    echo ""

    for jail in $(fail2ban-client status | grep "Jail list:" | sed 's/.*://;s/,//g'); do
        echo "--- $jail ---"
        fail2ban-client status "$jail" 2>/dev/null || true
        echo ""
    done
}

unban_ip() {
    local ip="$1"
    local jail="${2:-}"

    if [[ -z "$jail" ]]; then
        log_info "Unbanning $ip from all jails..."
        fail2ban-client unban "$ip" 2>/dev/null || true
    else
        log_info "Unbanning $ip from $jail..."
        fail2ban-client set "$jail" unbanip "$ip" 2>/dev/null || true
    fi
}

ban_ip() {
    local ip="$1"
    local jail="${2:-sshd}"

    log_info "Banning $ip in jail $jail..."
    fail2ban-client set "$jail" banip "$ip"
}

interactive_setup() {
    echo "=============================================="
    echo "AIDN - Fail2ban Setup"
    echo "=============================================="
    echo ""

    read -p "SSH Port [10022]: " ssh_port
    ssh_port="${ssh_port:-10022}"

    read -p "Ban time in seconds [3600]: " ban_time
    ban_time="${ban_time:-3600}"

    read -p "Max retry attempts [3]: " max_retry
    max_retry="${max_retry:-3}"

    echo ""
    read -p "Setup Arma Reforger protection? [y/N]: " -n 1 -r
    echo
    setup_arma="${REPLY}"

    echo ""
    echo "Configuration:"
    echo "  SSH Port: $ssh_port"
    echo "  Ban Time: $ban_time seconds"
    echo "  Max Retry: $max_retry"
    echo ""

    read -p "Proceed with setup? [y/N]: " -n 1 -r
    echo

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_warn "Aborted"
        exit 0
    fi

    install_fail2ban
    configure_jail_local "$ssh_port" "$ban_time" "600" "$max_retry"
    create_sshd_ddos_filter

    if [[ $setup_arma =~ ^[Yy]$ ]]; then
        read -p "Arma Reforger log path [/var/log/arma-reforger.log]: " arma_log
        arma_log="${arma_log:-/var/log/arma-reforger.log}"
        setup_arma_reforger "$arma_log"
    fi

    restart_fail2ban
    show_status

    echo ""
    echo -e "${GREEN}Fail2ban configured successfully!${NC}"
    echo ""
}

print_usage() {
    echo "Usage: $0 [COMMAND] [OPTIONS]"
    echo ""
    echo "Commands:"
    echo "  setup          Interactive fail2ban setup"
    echo "  status         Show fail2ban status"
    echo "  ban IP [JAIL]  Ban an IP address"
    echo "  unban IP       Unban an IP address"
    echo "  restart        Restart fail2ban"
    echo ""
    echo "Examples:"
    echo "  $0 setup"
    echo "  $0 status"
    echo "  $0 ban 1.2.3.4 sshd"
    echo "  $0 unban 1.2.3.4"
    echo ""
}

main() {
    check_root

    case "${1:-}" in
        setup)
            interactive_setup
            ;;
        status)
            show_status
            ;;
        ban)
            if [[ -z "$2" ]]; then
                log_error "IP address required"
                echo "Usage: $0 ban IP [JAIL]"
                exit 1
            fi
            if ! validate_ip "$2"; then
                log_error "Invalid IP address: $2"
                exit 1
            fi
            ban_ip "$2" "${3:-sshd}"
            ;;
        unban)
            if [[ -z "$2" ]]; then
                log_error "IP address required"
                echo "Usage: $0 unban IP [JAIL]"
                exit 1
            fi
            if ! validate_ip "$2"; then
                log_error "Invalid IP address: $2"
                exit 1
            fi
            unban_ip "$2" "${3:-}"
            ;;
        restart)
            restart_fail2ban
            ;;
        *)
            print_usage
            ;;
    esac
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
