#!/bin/bash
#
# AIDN - SSH Hardening Script
# Configures secure SSH with RSA key authentication on Debian servers
#

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
SSH_PORT="${SSH_PORT:-10022}"
SSHD_CONFIG="/etc/ssh/sshd_config"
SSHD_CONFIG_BACKUP="/etc/ssh/sshd_config.backup.$(date +%Y%m%d%H%M%S)"

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

backup_sshd_config() {
    log_info "Backing up SSH configuration to $SSHD_CONFIG_BACKUP"
    cp "$SSHD_CONFIG" "$SSHD_CONFIG_BACKUP"
}

configure_sshd() {
    log_info "Configuring SSH daemon..."

    cat > "$SSHD_CONFIG" << 'EOF'
# AIDN SSH Hardening Configuration
# Generated by AIDN ssh-hardening.sh

# Network
Port SSH_PORT_PLACEHOLDER
AddressFamily inet
ListenAddress 0.0.0.0

# Protocol
Protocol 2

# Host Keys
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ed25519_key

# Authentication
PermitRootLogin prohibit-password
PubkeyAuthentication yes
AuthorizedKeysFile .ssh/authorized_keys

# Disable password authentication (RSA keys only)
PasswordAuthentication no
PermitEmptyPasswords no
ChallengeResponseAuthentication no

# Disable other authentication methods
KerberosAuthentication no
GSSAPIAuthentication no
HostbasedAuthentication no

# Security
StrictModes yes
MaxAuthTries 3
MaxSessions 5
LoginGraceTime 30

# Disable forwarding (enable if needed)
AllowTcpForwarding no
X11Forwarding no
AllowAgentForwarding no

# Logging
SyslogFacility AUTH
LogLevel VERBOSE

# Keep alive
ClientAliveInterval 300
ClientAliveCountMax 2

# Misc
PrintMotd no
PrintLastLog yes
TCPKeepAlive yes
UsePAM yes
AcceptEnv LANG LC_*

# Subsystem
Subsystem sftp /usr/lib/openssh/sftp-server
EOF

    # Replace port placeholder
    sed -i "s/SSH_PORT_PLACEHOLDER/$SSH_PORT/" "$SSHD_CONFIG"

    log_info "SSH configured on port $SSH_PORT"
}

setup_ssh_keys() {
    local user="${1:-root}"
    local home_dir

    if [[ "$user" == "root" ]]; then
        home_dir="/root"
    else
        home_dir="/home/$user"
    fi

    local ssh_dir="$home_dir/.ssh"
    local auth_keys="$ssh_dir/authorized_keys"

    log_info "Setting up SSH directory for $user"

    mkdir -p "$ssh_dir"
    chmod 700 "$ssh_dir"
    touch "$auth_keys"
    chmod 600 "$auth_keys"

    if [[ "$user" != "root" ]]; then
        chown -R "$user:$user" "$ssh_dir"
    fi

    log_info "SSH directory configured at $ssh_dir"
    log_warn "Add your RSA public key to: $auth_keys"
}

generate_host_keys() {
    log_info "Regenerating SSH host keys..."

    rm -f /etc/ssh/ssh_host_*

    ssh-keygen -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N "" -q
    ssh-keygen -t ed25519 -f /etc/ssh/ssh_host_ed25519_key -N "" -q

    log_info "New host keys generated"
}

test_sshd_config() {
    log_info "Testing SSH configuration..."

    if sshd -t; then
        log_info "SSH configuration is valid"
        return 0
    else
        log_error "SSH configuration test failed!"
        log_warn "Restoring backup configuration..."
        cp "$SSHD_CONFIG_BACKUP" "$SSHD_CONFIG"
        return 1
    fi
}

restart_sshd() {
    log_info "Restarting SSH daemon..."
    systemctl restart sshd

    if systemctl is-active --quiet sshd; then
        log_info "SSH daemon restarted successfully"
    else
        log_error "SSH daemon failed to start!"
        exit 1
    fi
}

print_connection_info() {
    local ip
    ip=$(hostname -I | awk '{print $1}')

    echo ""
    echo "=================================================="
    echo -e "${GREEN}SSH Hardening Complete${NC}"
    echo "=================================================="
    echo ""
    echo "Connection details:"
    echo "  Port: $SSH_PORT"
    echo "  IP: $ip"
    echo ""
    echo "Connect with:"
    echo "  ssh -p $SSH_PORT -i /path/to/private_key root@$ip"
    echo ""
    echo -e "${YELLOW}IMPORTANT:${NC} Ensure your RSA public key is in:"
    echo "  /root/.ssh/authorized_keys"
    echo ""
    echo -e "${RED}WARNING:${NC} Password authentication is DISABLED"
    echo "Keep your current session open until you verify key access!"
    echo "=================================================="
}

main() {
    echo "=============================================="
    echo "AIDN - SSH Hardening Script"
    echo "=============================================="
    echo ""

    check_root
    backup_sshd_config
    configure_sshd
    setup_ssh_keys "root"

    read -p "Regenerate SSH host keys? [y/N]: " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        generate_host_keys
    fi

    if test_sshd_config; then
        read -p "Restart SSH daemon now? [y/N]: " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            restart_sshd
        else
            log_warn "Remember to restart SSH: systemctl restart sshd"
        fi
    fi

    print_connection_info
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
